<?php
/**
 * Created by PhpStorm.
 * User: kieran
 * Date: 7/30/16
 * Time: 12:31 PM
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */

function book_explorer_form_book_admin_settings_alter(array &$form, FormStateInterface $form_state, $form_id) {
  drupal_set_message('Boo!');
  drupal_set_message('Here is $form.');
  ksm($form);
  drupal_set_message('Here is $form_state.');
  ksm($form_state);
  $book_manager = \Drupal::service('book.manager');
  drupal_set_message('Here is the book manager');
  ksm($book_manager);
  $books = $book_manager->getAllBooks();
  drupal_set_message('Here is the books array');
  ksm($books);
  if ( sizeof( $books ) > 0 ) {
    $form['book_explorer'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Book Explorer'),
      '#description' => t(
        'Select the books that should have explorer blocks created for them.'),
      '#options' => array(),
    );
    foreach ($books as $book) {
      $form['book_explorer']['#options'][$book['nid']] = $book['title'];
    }
  }
}
